version: 2.1

orbs:
  # Choose either one of the orbs below
  aws-cli: circleci/aws-cli@2.0.3

# Define a job to be invoked later in a workflow.
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["78:92:60:db:42:43:b5:19:63:2d:05:08:f5:f3:5c:32"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

# Invoke jobs via workflows
workflows:
  build-workflow :
    jobs:
      - create_infrastructure
      - configure_infrastructure
