version: 2.1

orbs:
  # Choose either one of the orbs below
  aws-cli: circleci/aws-cli@2.0.3

# Define a job to be invoked later in a workflow.
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

# Invoke jobs via workflows
workflows:
  build-workflow :
    jobs:
      - create_infrastructure
